### ISSUE TITLE
State not updating when selector changes

### ISSUE THREAD

**Issue by Tirzono** [dai-shi/use-zustand#1]
It looks like `useZustand` does not take into account to update the state when the selector changes.

See codesandbox for an example:

https://codesandbox.io/s/dazzling-shockley-xyjw1d?file=/src/App.js

```javascript
import { createStore } from 'zustand/vanilla';
import { useZustand } from 'use-zustand';
import { useCallback, useState } from 'react';

const store = createStore(() => ({
  values: ['zero', 'one', 'two', 'three'],
}));

const valuesSelector = (state) => state.values;

export default function App() {
  const [index, setIndex] = useState(0);
  const selector = useCallback((state) => state.values[index], [index]);
  const value = useZustand(store, selector);
  const values = useZustand(store, valuesSelector);

  return (
    <div>
      {values.map((item, index) => (
        <button
        key={index}
        onClick={() => setIndex(index)}
        >
        {index}
        </button>
      ))}
      <ul>
        <li>Index: {index}</li>
        <li>Value: {value}</li>
      </ul>
    </div>
  );
}
```

**Comment by dai-shi** [comment]
Good catch. I thought I took care of it, but obviously there's a bug. I'll compare with other working projects.

Give me some time.

**Comment by dai-shi** [comment]
(Note to myself: I think I misunderstood something when implementing `use-zustand`. It's basically from `jotai`'s useAtomValue, but for the selector part, I should have used the logic in `use-context-selector`. This applies to [use-valtio](https://github.com/dai-shi/use-valtio) too.)

**Comment by dai-shi** [comment]
#2 fixes it: https://codesandbox.io/s/smoosh-water-0mkn6m

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-zustand/v/0.0.2

**Comment by dai-shi** [comment]
Published https://www.npmjs.com/package/use-zustand/v/0.0.3 with a fix.

**Comment by Tirzono** [comment]
Thanks for fixing this issue. One thing I notice though is that when clicking one of the numbers causes the selector to run 4 times. Also: when the component rerenders (for example because some other state updated) and the selector didn't change and the state of the store also didn't change, it still runs the selector 2 times. I can remember that in v3 this was not the case. Isn't it an idea to bring back the implementation we had in v3 in `use-zustand`? If that's out-of-scope of this project then that's okay, then I'll just directly do that in my code, but was just wondering if that would be an improvement in this project.

```javascript
const useZustand(api, selector, equalityFn = Object.is) => {
  const [, forceUpdate] = useReducer((c) => c + 1, 0) as [never, () => void]

  const state = api.getState()
  const stateRef = useRef(state)
  const selectorRef = useRef(selector)
  const equalityFnRef = useRef(equalityFn)
  const erroredRef = useRef(false)

  const currentSliceRef = useRef<StateSlice>()
  if (currentSliceRef.current === undefined) {
    currentSliceRef.current = selector(state)
  }

  let newStateSlice: StateSlice | undefined
  let hasNewStateSlice = false

  // The selector or equalityFn need to be called during the render phase if
  // they change. We also want legitimate errors to be visible so we re-run
  // them if they errored in the subscriber.
  if (
    stateRef.current !== state ||
    selectorRef.current !== selector ||
    equalityFnRef.current !== equalityFn ||
    erroredRef.current
  ) {
    // Using local variables to avoid mutations in the render phase.
    newStateSlice = selector(state)
    hasNewStateSlice = !equalityFn(
      currentSliceRef.current as StateSlice,
      newStateSlice
    )
  }

  // Syncing changes in useEffect.
  useIsomorphicLayoutEffect(() => {
    if (hasNewStateSlice) {
      currentSliceRef.current = newStateSlice
    }
    stateRef.current = state
    selectorRef.current = selector
    equalityFnRef.current = equalityFn
    erroredRef.current = false
  })

  const stateBeforeSubscriptionRef = useRef(state)
  useIsomorphicLayoutEffect(() => {
    const listener = () => {
      try {
        const nextState = api.getState()
        const nextStateSlice = selectorRef.current(nextState)
        if (
          !equalityFnRef.current(
            currentSliceRef.current,
            nextStateSlice
          )
        ) {
          stateRef.current = nextState
          currentSliceRef.current = nextStateSlice
          forceUpdate()
        }
      } catch (error) {
        erroredRef.current = true
        forceUpdate()
      }
    }
    const unsubscribe = api.subscribe(listener)
    if (api.getState() !== stateBeforeSubscriptionRef.current) {
      listener() // state has changed before subscription
    }
    return unsubscribe
  }, [])

  return hasNewStateSlice
    ? newStateSlice
    : currentSliceRef.current
}
```

https://github.com/pmndrs/zustand/blob/4d8003b363cb06ee5b1da498300a60576419485a/src/react.ts

**Comment by dai-shi** [comment]
> If that's out-of-scope of this project

Yes, it's out of the scope. This project is for react 18+ and never uses `useRef`.

> when clicking one of the numbers causes the selector to run 4 times.

But, 4 times sound too many. I'd expect twice. I'll see how it goes.

**Comment by dai-shi** [comment]
#4 should fix it: https://codesandbox.io/s/laughing-platform-mmek9d

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-zustand/v/0.0.4

**Comment by Tirzono** [comment]
Amazing, I can confirm that works. Thank you for your help.
