### ISSUE TITLE
data not updated

### ISSUE THREAD

**Issue by xyhxx** [dai-shi/use-zustand#11]
I used examples:01_counter for testing, and after clicking inc, the count did not change.
The same goes for the online example in the documentation.

I saw line 21 of the source code, comparing `store. getState()` and `nextState`,there are always be the same.

``` ts
if (Object.is(state, nextState) && prev[1] === store) {
    return prev;
  }
```

**Comment by dai-shi** [comment]
Ahhh, nice catch. I think our fix in #9 is incomplete. Thanks for reporting.

**Comment by xyhxx** [comment]
Can we add prevState to the `sliceFromReducer`, like:

```ts
const [[sliceFromReducer, storeFromReducer], rerender] = useReducer<
  Reducer<
    readonly [{ slice: Slice; state: State }, StoreApi<State>],
    boolean | undefined
  >,
  undefined
>(
  (prev, fromSelf?: boolean) => {
    if (fromSelf) {
      return [{ slice, state }, store];
    }
    const nextState = store.getState();
    if (Object.is(prev[0].state, nextState) && prev[1] === store) {
      return prev;
    }

    const nextSlice = selector(nextState);
    if (areEqual(prev[0].slice, nextSlice) && prev[1] === store) {
      return prev;
    }
    return [{ slice: nextSlice, state: nextState }, store];
  },
  undefined,
  () => [{ state, slice }, store],
);
...
return sliceFromReducer.slice;
```
And change `sliceFromReduce `to `stateFromReduce`.

I have another question, why compare prevState and nextState first, Is that to prevent unnecessary `selector` use?

If this comparison is removed, the problem should also be resolved.

**Comment by dai-shi** [comment]
Yes, #12 should fix it! It has never implemented correctly. 😓

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-zustand/v/0.2.0

Thanks for your help.
