### ISSUE TITLE
Data not retain correctly with Persist, when using partialize

### ISSUE THREAD

**Issue by phamyqb** [dai-shi/use-zustand#13]
data not retain correct when using partialize
`export const useBoundStore = createStore(
  persist(
    (set, get) => ({
      foo: 0,
      bar: 1,
    }),
    {
      partialize: (state) => ({ foo: state.foo }),
    },
  ),
)`

Persisted State only work without partialize

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
Can you create a minimal reproduction with StackBlitz?
You can fork https://stackblitz.com/github/zustandjs/use-zustand/tree/main/examples/01_counter.

**Comment by phamyqb** [comment]
Thanks @dai-shi  for quick response, seems working for me now, I switched to use `create` from zustand instead of `zustand/vanilla`
