### ISSUE TITLE
May tearing happen in non-concurrent rendering?

### ISSUE THREAD

**Issue by recover758126** [dai-shi/use-zustand#15]
If I don`t use concurrent, tearing will be happen?

**Comment by dai-shi** [comment]
No. It will happen only if you (or some code) explicitly triggers concurrent rendering.
That's one of the reasons they gave up "concurrent mode", which is all or nothing, tearing can happen everywhere.

**Comment by recover758126** [comment]
if (storeFromReducer !== store) {
    const slice = selector(state);
    rerender([slice, store, state]);
    return slice;
  }
 I have another question that what will happen if i removed this in useZustand hook here https://github.com/zustandjs/use-zustand/blob/7171384c7711def80a6fc0a7d42d192b4a50c835/src/index.ts#L42

**Comment by dai-shi** [comment]
It's to handle store changes. Unless you change the `store` you pass to the hook, nothing breaks.
