### ISSUE TITLE
`fromSelf` is actually always a truthy value

### ISSUE THREAD

**Issue by itswillta** [dai-shi/use-zustand#8]
In the current source code, `fromSelf` is actually always a truthy value because `rerender` in `store.subscribe` in `useEffect` is always called with 2 truthy parameters.

```ts
import { useEffect, useMemo, useReducer } from 'react';
import type { DispatchWithoutAction, Reducer } from 'react';
import type { StoreApi } from 'zustand';

export function useZustand<State, Slice>(
  store: StoreApi<State>,
  selector: (state: State) => Slice,
  areEqual: (a: Slice, b: Slice) => boolean = Object.is,
) {
  const state = store.getState();
  const slice = useMemo(() => selector(state), [state, selector]);
  const [[sliceFromReducer, storeFromReducer], rerender] = useReducer<
    Reducer<readonly [Slice, StoreApi<State>], boolean | undefined>,
    undefined
  >(
    (prev, fromSelf?: boolean) => {
      if (fromSelf) {
        return [slice, store];
      }
      const nextState = store.getState();
      if (Object.is(state, nextState) && prev[1] === store) {
        return prev;
      }
      const nextSlice = selector(nextState);
      if (areEqual(prev[0], nextSlice) && prev[1] === store) {
        return prev;
      }
      return [nextSlice, store];
    },
    undefined,
    () => [slice, store],
  );
  useEffect(() => {
    const unsubscribe = store.subscribe(rerender as DispatchWithoutAction); // This will always pass 2 truthy parameters to "rerender"
    (rerender as DispatchWithoutAction)();
    return unsubscribe;
  }, [store]);
  if (storeFromReducer !== store) {
    rerender(true);
    return slice;
  }
  return sliceFromReducer;
}
```

This basically makes the comparisons in the reducer useless. I tried using this library in my project and discovered this. This makes every component using this hook rerender no matter what the slice/selector is. cc @dai-shi

**Comment by dai-shi** [comment]
Nice catch. So, do you mean this?

```diff
-  const unsubscribe = store.subscribe(rerender as DispatchWithoutAction);
+  const unsubscribe = store.subscribe(() => rerender());
```

**Comment by itswillta** [comment]
> Nice catch. So, do you mean this?
> 
> ```diff
> -  const unsubscribe = store.subscribe(rerender as DispatchWithoutAction);
> +  const unsubscribe = store.subscribe(() => rerender());
> ```

Yeah. I actually forked the code and did the exact fix myself before reporting the issue here.

**Comment by dai-shi** [comment]
Great. Would you like to send a PR please?

**Comment by itswillta** [comment]
> Great. Would you like to send a PR please?

OK I'm opening it. Btw, is this line in `useEffect` necessary?

```ts
    (rerender as DispatchWithoutAction)();
```

Also after that fix, these lines seem to prevent it from re-rendering when you only change a slice of the state:

```ts
      if (Object.is(state, nextState) && prev[1] === store) {
        return prev;
      }
 ```
 
 This is the working hook that I'm personally using:
 
 ```ts
import { useEffect, useMemo, useReducer, Reducer } from 'react';
import { StoreApi } from 'zustand';

export function useZustand<State, Slice>(
  store: StoreApi<State>,
  selector: (state: State) => Slice,
  areEqual: (a: Slice, b: Slice) => boolean = Object.is,
) {
  const state = store.getState();
  const slice = useMemo(() => selector(state), [state, selector]);
  const [[sliceFromReducer, storeFromReducer], rerender] = useReducer<
    Reducer<readonly [Slice, StoreApi<State>], boolean | undefined>,
    undefined
  >(
    (prev, fromSelf?: boolean) => {
      if (fromSelf) return [slice, store];

      const nextState = store.getState();
      const nextSlice = selector(nextState);

      if (areEqual(prev[0], nextSlice) && prev[1] === store) return prev;

      return [nextSlice, store];
    },
    undefined,
    () => [slice, store],
  );

  useEffect(() => {
    const unsubscribe = store.subscribe(() => rerender());

    return unsubscribe;
  }, [store]);

  if (storeFromReducer !== store) {
    rerender(true);

    return slice;
  }

  return sliceFromReducer;
}
```

**Comment by dai-shi** [comment]
> Btw, is this line in `useEffect` necessary?

Yes, it's required to cover an edge case.

> Also after that fix, these lines seem to prevent it from re-rendering when you only change a slice of the state:

It's also necessary to keep the same optimization `zustand` has. If you change a slice, you should change the state too. It's the immutability contract.

> This is the working hook that I'm personally using:

It might work for your case. You could even try a simpler one with `useState` without `useReducer`.

**Comment by dai-shi** [comment]
```js
export function useZustandSimple(store, selector) {
  const [slice, setSlice] = useState(() => selector(store.getState()));
  useEffect(() => store.subscribe(() => setSlice(selector(store.getState()))), []);
  return slice;
}
```

**Comment by itswillta** [comment]
I'm curious to know what the edge cases are. I tried your suggestion and it's working for my use cases. Thanks!

**Comment by dai-shi** [comment]
useEffect runs asynchronously and there's a chance that zustand state is changed after it's read in render.

useSyncExternalStore handles such cases and more.

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/use-zustand/v/0.1.1
